services:
  backend:
    build: ./backend
    container_name: family-backend
    volumes:
      - ./backend/staticfiles:/app/staticfiles
      - ./backend/media:/app/media
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000 --timeout 600
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: family-frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: family-db
    environment:
      POSTGRES_DB: familydb
      POSTGRES_USER: ianadmin
      POSTGRES_PASSWORD: supersecurepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
